[package]
name = "starkmark_test"
version = "0.1.0"
edition = "2023_10"

[dependencies]
starknet = ">=2.6.4"
alexandria_storage = { git = "https://github.com/keep-starknet-strange/alexandria.git" }

[[target.starknet-contract]]